### ISSUE TITLE
StringArrayParser does not support Strings surrounded with hyphens

### ISSUE THREAD

**Issue by michaelrall** [aloneguid/config#39]
It is not possible to set string values within an string array parameter that have whitespaces (e.g. filenames /paths). Surrounding with hyphens does not help, because the StringArrayParser justs splits by whitespace.

Example:
`TestArrayWSpace="testArrayA and B","testArrayC","TestArrayD or E"`
will result in
`testArrayA|and|B|testArrayC|TestArrayD|or|E`
instead of
`testArrayA and B|testArrayC|TestArrayD or E`

Solution:
Due to the fact, that the commandline parser removes the hypens, additional single hyphens could be used to mark these strings. The StringArrayParser additionally needs to respect those (maybe first run a regex to extract the single-hyphend strings) (StringArrayParser.cs:21).

Example:
`TestArrayWSpace="'testArrayA and B'","testArrayC","'TestArrayD or E'"`

**Comment by aloneguid** [comment]
I see your point, sounds interesting. In order to do that we need to implement some sort of escaping mechanism like command line does, to be able to include quotes in quotes etc.

Are you up for implementing this?

**Comment by michaelrall** [comment]
Yes I could do that.

At first I would search and evaluate possible escaping-mechnisms that would work for all store-types so that we won't have different syntax for different stores.

Do you have a place where you would put that information or should we collect that in this issues' comments?

**Comment by aloneguid** [comment]
Great. I don't mind, I think ideally it should be described in markdown documentation, but we can also keep the discussion going here.

**Comment by michaelrall** [comment]
just for organization: i would pull your lib, create branch for this issue, make my changes and push the new branch, then you would merge it if everyting fits?

**Comment by aloneguid** [comment]
hey @michaelrall you'd usually fork, make changes and create a PR in GitHub, this tutorial explains how https://guides.github.com/activities/forking/

**Comment by michaelrall** [comment]
aah, now I see (it's my first time to contribute to github), but the concept seems to be the same as my first thought :-P

**Comment by michaelrall** [comment]
Oh boy, after reading some stuff about different escaping mechanism for the supported formats (JSON, YAML, CommandLine, etc.) that doesn't look so good. Basically one would have to use different escaping-characters for different stores,

A possible root of the problem is, that internally the string-array is converted to comma-separated-string and this value is stored as "single" string to the store instead of using the appropriate store-type for an array (see LogicTest.WriteStringArrayTest()). Basically internally string[] should be always used and serialization should be postponed to the last possible point.
I see that would be no trivial changes - but at the moment I don't see an other good solution using special formatting within the string itself.

**Comment by michaelrall** [comment]
maybe one could use the JSON-Array-Format to represent string-arrays, but that would be a breaking change for existing config-entries

**Comment by aloneguid** [comment]
@michaelrall yes it's a pain :( A lot of stores, if not most,  do not support string arrays for serialisation, so this has to be converted to a string somehow anyway. The problem with JSON is that characters [need to be escaped too](http://json.org/) plus you have brackets and quotes around values, so in some terms it's harder that command line syntax. 

Although when writing back to JSON, it's nice to have string array value as this is supported natively, instead of a string value. I suppose some internal changes are to be made, but it's harder.

TBH when I'm editing configuration store comma-separated (or space separated) values are the best, so I'm personally keen to have something really simple with less human errors. In my case configuration is often edited by not very technical people as well (users, support etc.).

**Comment by aloneguid** [comment]
@michaelrall btw why not adopting command-line syntax? I.e. space-separated values. If they have spaces they're taken in quotes. Quotes are escaped etc.

**Comment by michaelrall** [comment]
I absolutely agree to have a simple syntax, because that's one of the goals of config.net. Maybe one could accept the current issue as limitation.

**Comment by aloneguid** [comment]
Sorry for the delay. Have you decided to implement this or accept the current limitations? :)

**Comment by michaelrall** [comment]
To be honest, as long I don't have a good solution that aligns with the spirit of config.net I think I'll accept this as limitation - maybe there will be a sudden flash of inspiration :-)

**Comment by aloneguid** [comment]
That's fine. TBH i'm not using string arrays because of the same reason as you are :) Just had some thoughts on this though:

- as a first stage we could implement a syntax similar to command-line
- some stores like JSON have arrays support internally, however `IConfigStore` does not expose any metadata allowing them to utilise this. I'm not sure whether it's good or bad. Pros - extremely easy to implement new stores. Cons - arrays don't feel "native". Maybe there can be some extra metadata exposed to future implementations of `IConfigStore` where they can optionally use it to better serialise/deserialise them. Yaml store is another example where arrays are supported.

**Comment by aloneguid** [comment]
I've done sort of a simple implementation, it's better than the current one but not perfect, available in 4.4.0
